# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache common
        uses: actions/cache@v2
        with:
          path: |
            **/dist
            **/.rush/temp
            common/temp/node_modules
            common/temp/projects
          key: ${{ runner.os }}-${{ hashFiles('**/common/config/rush/pnpm-lock.yaml') }}

      - name: Build
        run: |
          node common/scripts/install-run-rush.js install --no-link
          node common/scripts/install-run-rush.js link
          node common/scripts/install-run-rush.js build
          node common/scripts/install-run-rush.js typecheck
          node common/scripts/install-run-rush.js lint
          node common/scripts/install-run-rush.js relay:validate
          node common/scripts/install-run-rush.js test

      - name: Deploy
        run: |
          yarn global add heroku
          node common/scripts/install-run-rush.js deploy:apps
        if: github.ref == 'refs/heads/master'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
